services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: connect
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  eureka-server:
    image: connectnavigation.azurecr.io/eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

  features-microservice:
    image: connectnavigation.azurecr.io/features-microservice
    container_name: features-mircoservice
    build:
      context: ./features-microservice
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - 'eureka-server'
      - 'postgres'

  routes-microservice:
    image: connectnavigation.azurecr.io/routes-microservice
    container_name: routes-mircoservice
    build:
      context: ./routes-microservice
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - 'eureka-server'

  api-gateway:
    image: connectnavigation.azurecr.io/api-gateway
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - eureka-server

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: