name: Backend CI

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW }}

      - name: Set up JDK    
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 17

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests -Pproduction

      - name: Create dist directory
        run: mkdir -p dist/target && echo "keep me" > dist/target/.keepme

      - name: Move build files to dist
        run: mv target/*.jar bootstrap Dockerfile dist

      - name: Push to bachend branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: backend
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}
          MESSAGE: "Automatic Commit: ({sha}) {msg}"

